gchq/CyberChef

Gruntfile.js
src/html/index.html

Download Cyber chef now downloads the HTML file when clicked in browsers

---

test/tests/operations/FlowControl.js

Adds the following tests:
+ `Jump: skips 0`
+ `Jump: skips 1`
+ `Jump: skips negatively`
+ `Conditional Jump: skips 1`
+ `Conditional Jump: skips negatively`

Add Jump and Conditional Jump tests

---

src/web/OperationsWaiter.js

...and removed popovers when favourites are dragged out.

Fixed popover bug in search

---

Gruntfile.js
src/web/html/index.html

Still some warnings and notices, but they are inconsequential.
Additionally added it to `grunt prod` however due to how long it takes to run, maybe it shouldn't be there.

Made changes to fix accessibility errors

---

src/core/operations/Code.js

Because damn this was bad. 
Here you go.

Clean up: Removed redundant assignments

---

src/core/config/OperationConfig.js
src/core/operations/Cipher.js
src/core/operations/PublicKey.js

X.509 Parser now doesn't break with signatures that it can't parse

X.509 Parser bug

---

src/core/Utils.js
src/core/config/OperationConfig.js
src/core/operations/StrUtils.js

Fixed global matching for simple strings in 'Find / Replace' operation

---

src/core/Utils.js
src/core/config/Categories.js
src/core/config/OperationConfig.js
src/core/operations/ByteRepr.js
src/core/operations/Cipher.js
src/core/operations/Rotate.js
test/index.js
test/tests/operations/ByteRepr.js
test/tests/operations/Cipher.js

Adds [Bifid Cipher](https://en.wikipedia.org/wiki/Bifid_cipher) Encoding and Decoding operations, as well as a function for generating Polybius squares.
>Just came up in an ARG I've been playing recently so I decided to add it.

Feature: Bifid Cipher

---

src/web/html/index.html
src/web/stylesheets/index.css
src/web/stylesheets/themes/_geocities.css

Added a GeoCities theme

---

src/web/Manager.js

Fixed bug where clicking up and down arrows on numeric inputs would not trigger an auto-bake

Bug fix: numeric input change trigger

---

src/core/operations/Numberwang.js

Fixed the Numberwang algorithm to correctly recognise recently discovered Numberwang values. Fixes #204
The following Numberwang formats are now recognised: 
3i
-2275
2.4
√14
885%
F0rty-s1x
Shinty-six
Filth-hundred and neeb
http://numberwang.wikia.com/wiki/Numberwang_Wikia:All_numbers

Numberwang fix

---

.eslintrc.json
package-lock.json
package.json
src/core/config/Categories.js
src/core/config/OperationConfig.js
src/core/config/modules/Default.js
src/core/operations/XKCD.js
src/web/HTMLOperation.js

A random number generator based on [XKCD #221](https://xkcd.com/221/).

XKCD Random Number

---

.travis.yml
Gruntfile.js
package-lock.json
package.json
src/web/App.js
src/web/static/robots.txt
src/web/static/sitemap.js

This PR adds a dynamically generated `sitemap.xml` file to production builds, showing URLs for every operation.
It also adds a `robots.txt` file to disallow crawling of `cyberchef.htm`, the inline version.

Sitemap and robots.txt

---

README.md

To reflect the new OSS CLA process

Update CLA info in README

---

src/core/operations/TranslateDateTimeFormat.mjs
test/index.mjs
test/tests/operations/TranslateDateTimeFormat.mjs

Fixes #334.
First contribution here - so hope I've done everything right!
This just implements the suggested fix, which appears to work. I've also added a few tests - hope that's alright.

Fix date time

---

package-lock.json
package.json
src/core/config/Categories.json
src/core/operations/FromMessagePack.mjs
src/core/operations/ToMessagePack.mjs
test/tests/operations/Code.mjs

Adds operations and tests for [Messagepack](https://msgpack.org/index.html).
Closes #326.

Added messagepack operations

---

src/core/lib/BitwiseOp.mjs
src/core/operations/XOR.mjs

Adds Cascade scheme to the XOR operation, to resolve #268.
See previous PR for more details (#297)

Added Cascade XOR (new)

---

src/core/operations/ToBase64.mjs

Modified description of ToBase64 operation

---

src/core/operations/ToTable.mjs
src/web/OutputWaiter.mjs

Fixes the XSS bugs as reported in #483 and #484 .

Bug Fix: Fix XSS in Magic button and To Table operations

---

src/web/InputWaiter.mjs
src/web/Manager.mjs
src/web/html/index.html

Adds a button which allows the user to select a file from their filesystem for the recipe input, using the built in file prompt. (Requested in #460 )

Feature: Open file button

---

package-lock.json
package.json

Some security updates in this one, not sure how much it affects us but it pays to stay up to date.

Update yara to v3.9.0

---

src/core/operations/Fork.mjs
src/core/operations/Subsection.mjs

Fix bug in fork operation which caused #498 .

Bug Fix: Fix fork operation not setting ingredient values correctly.

---

src/core/vendor/DisassembleX86-64.mjs

Turns out the updated disassembler didn't work right. Not really sure how I missed it but here's a fix.

Fix disassembler issue

---

src/core/Utils.mjs
src/core/lib/Hex.mjs

Resolves https://github.com/gchq/CyberChef/issues/464
Added Percent to hex delimiter options. Enables user to URL Encode all characters.

Feature: Added Percent delimiter for "To Hex" operation

---

src/core/operations/ExtractFiles.mjs

Noticed a "TODO" in the description field. Just added a basic description. Feel free to add more if needed.

Added description to Extract Files

---

src/web/stylesheets/themes/_classic.css
src/web/stylesheets/themes/_dark.css
src/web/stylesheets/themes/_geocities.css
src/web/stylesheets/themes/_solarizedDark.css
src/web/stylesheets/themes/_solarizedLight.css
src/web/stylesheets/utils/_overrides.css

Fixes #599 (also for new Solarized themes (and geocities :P))

Fixed tables in alternative themes

---

package-lock.json
package.json

- Update nightwatch dependencies to remove vulnerability.
- Update ChromeDriver to fix [build issues](https://travis-ci.org/gchq/CyberChef/builds/603254095#L627)

Update nightwatch & chromedriver

---

src/web/html/index.html

auto focus on search bar and made searchbar and text area tab-able

---

package-lock.json
package.json
src/core/operations/YARARules.mjs
tests/node/tests/operations.mjs

Figured it would be pertinent to add a test for node since that's a different target for emscripten builds.
EDIT: Apparently something about this build has doubled the size of the YARA package - going to investigate

Update yara & openssl versions & add yara node test

---

src/core/lib/FileSignatures.mjs

Operations added for:
Extract Files operation
Operations Added:
XZ extractor.
BZIP2 extractor.
GIF extractor.

Added extractors for BZIP2, XZ, GIF89

---

src/core/lib/FileSignatures.mjs

Added extractors for 32-bit and 64-bit Mach-O files.
Added a TAR extractor.
Also added an extra signature for 32-bit Mach-O files.

Added Tar and Mach-O extractors.

---

package-lock.json
src/core/lib/FileSignatures.mjs

File signatures for Linux .deb archives, Apple disk images, Smile :) files, Lua Bytecode and WebAssembly Binaries.

More file signatures.

---

src/core/operations/RegularExpression.mjs

Improved email regex

---

package-lock.json
src/core/lib/FileSignatures.mjs

The fileSize field in the header is the number of bytes after that point rather than the number of bytes including everything up to that point. 
So instead of fileSize we need fileSize + 8.
Since the fileSize field itself is 4 bytes long and the RIFF is 4 bytes.

WAV File extractor bug fix

---

package-lock.json
src/core/lib/FileSignatures.mjs

Extractors added for DMP(Windows Page Dump) PF(Windows Prefetch), PF(Windows 10 Prefetch), LNK (Windows Shortcut) and LZOP(LZOP compressed data).

More file extractors.

---

src/core/lib/FileSignatures.mjs

Added a Deb extractor and an extra JAR file signature, using the ZIP extractor for it.

DEB extractor

---

src/core/operations/Lorenz.mjs

This fixes #973 correcting the Lorenz custom pin setting.

Fix for issue #973 Lorenz custom selection

---

src/core/operations/LuhnChecksum.mjs
tests/operations/tests/LuhnChecksum.mjs

Luhn Checksum now generates both the checksum and checkdigit.

---

src/core/operations/Colossus.mjs

Hopefully soon CyberChef will move to node v12+ so need to keep on top of imports otherwise they will cause issues when CyberChef moves.

Very Small Correction for Import in Colossus

---

package-lock.json
src/core/config/Categories.json
src/core/operations/ConvertToNATOAlphabet.mjs
tests/operations/tests/ConvertToNATOAlphabet.mjs

Add an operation to convert text to the [phonetic NATO alphabet](https://en.wikipedia.org/wiki/NATO_phonetic_alphabet).

Operation: Convert to NATO alphabet

---

src/core/lib/FileSignatures.mjs

MP3 Extractor for all major tag versions added.

Mp3 extractor

---

src/core/operations/FromBinary.mjs
src/core/operations/ToBinary.mjs

"From Binary" doesn't represent the delimiter

---

src/core/operations/HaversineDistance.mjs
tests/operations/tests/HaversineDistance.mjs

Fixes #1141. Included new test for zero distance.

Fix for haversine distance bug

---

src/core/operations/ROT13.mjs
tests/operations/tests/Rotate.mjs

closes #1092 
I have added an argument to the ROT13 operation, to rotate numbers as well.

ROT with Numbers

---

src/core/operations/ParseDateTime.mjs
tests/node/tests/operations.mjs

Parse Date/Time displays incorrect week number

---

src/core/operations/JSONToCSV.mjs
tests/operations/tests/JSONtoCSV.mjs

JSON to CSV improvements

---

src/core/operations/AESEncrypt.mjs

Upon closer inspection, forge does support Authenticated Additional Data. So here it is. 
Closes #1008

AAD for AES Added

---

src/core/operations/JWTVerify.mjs
tests/operations/tests/JWTVerify.mjs

Enable verification of RSASHA256 and 512 tokens

Enable JWTVerify Verification of EC and RSA based JSON Web Tokens

---

src/core/lib/FileSignatures.mjs

I have added a PGP secring signatures and Mac OS X keyring extractor.

PGP secring signatures and Mac OS X keyring extractor added

---

README.md

Changed "or" to "and" because all the other sentence sections use "and".

Improved consistency

---

README.md

Fixed Crown Copyright link

---

src/core/lib/Charts.mjs
src/core/operations/ScatterChart.mjs
src/core/operations/SeriesChart.mjs

Fixes the security bug reported in https://github.com/gchq/CyberChef/issues/1265

Fix reflected XSS described in issue 1265

---

src/core/operations/ToBase45.mjs

fix "To Base45"

---

src/core/operations/Substitute.mjs

This adds support for UTF8-encoded characters in the input and the parameters of the Substitution operation. Closes #1348.

Support UTF8 encoded characters in Substitution operation

---

src/core/lib/Base64.mjs

Fix #1254 by adding input validation to `fromBase64()`

Added input validation to fromBase64()

---

src/core/operations/ConditionalJump.mjs
src/core/operations/Jump.mjs

Resolves #1345 
Resets the loop counter when the loop is finished.

reset loop counter after last run

---

src/core/lib/FileSignatures.mjs

Implements functionality to extract webp files.
Closes #1274

Implemented webp extractor

---

src/core/operations/Fork.mjs
src/core/operations/Merge.mjs
src/core/operations/Subsection.mjs
tests/operations/index.mjs
tests/operations/tests/Fork.mjs
tests/operations/tests/Subsection.mjs

Added the ability to nest a subsection/fork and a merge inside another.
Added tests for subsection.
Closes #1369

Added nesting to Merge/Fork/Subsection

---

src/core/operations/FromBase45.mjs
src/core/operations/FromBase85.mjs
tests/lib/TestRegister.mjs
tests/operations/index.mjs
tests/operations/tests/Base85.mjs

Add option to Remove non-alphabet chars
Did Base45 too

Base85 improvements

---

src/core/operations/Subsection.mjs

I was using the subsection operation and I was running multiple chained subsections. It was not immediately clear how to reset the effects of the subsection operation hence I have added a comment explicitly stating what to do.

Improve the subsection description

---

package-lock.json
src/core/config/Categories.json
src/core/lib/LS47.mjs
src/core/operations/LS47Decrypt.mjs
src/core/operations/LS47Encrypt.mjs
tests/operations/index.mjs
tests/operations/tests/LS47.mjs

LS47 encrypt/decrypt operations added.

Ls47 operations added.

---

src/web/stylesheets/utils/_overrides.css

Hello, I am done fixing bug select from this issue [#1406](https://github.com/gchq/CyberChef/issues/1406). Thank you

fix select when change theme

---

src/core/operations/JSONToCSV.mjs
tests/operations/tests/JSONtoCSV.mjs

feat: support boolean and null in JSON to CSV

---

src/core/lib/Protobuf.mjs
tests/operations/tests/Protobuf.mjs

Discovered a typo in the source that was the reason for #1350

fix protobuf field order, closes #1350

---

package-lock.json
package.json
src/core/operations/OpticalCharacterRecognition.mjs

Fixes #1344
* Update [tesseract.js](https://github.com/naptha/tesseract.js) to latest (improves performance greatly)
* Adjust OCR operation code to comply with [tesseract.js](https://github.com/naptha/tesseract.js) 3.0 API changes
* Add support for specifying the language for [tesseract.js](https://github.com/naptha/tesseract.js)
* Removed references to local copies of tesseract training data -- it was unclear to me why this was done originally

Fix Optical Character Recognition (OCR) operation

---

package-lock.json
package.json
src/core/operations/YARARules.mjs
tests/operations/tests/YARA.mjs
webpack.config.js

- Added option to display output of [Yara console module](https://yara.readthedocs.io/en/latest/modules/console.html) which allows arbitrary logging (request from @malvidin, mattnotmitt/libyara-wasm#6)
- Added option to hide rule compilation warnings
- Added tests for above two features and OpenSSL hashing support
- Fixed bug where match count could show 0
- Fixed bug where rule compilation warnings/errors would not show their messages

Update yara to 4.2.3, add console module support and fix misc bugs

---

src/core/operations/DNSOverHTTPS.mjs

Any chance this could be added?

Adding PTR to possible values for Resolver

---

src/core/operations/GenerateAllHashes.mjs
tests/operations/index.mjs
tests/operations/tests/GenerateAllHashes.mjs

Parameterise All hashes

---

src/core/operations/TripleDESDecrypt.mjs
src/core/operations/TripleDESEncrypt.mjs

Allow 16-byte keys for Triple DES

---

src/core/operations/ToTable.mjs

Markdown tables edition in a tools like [TheHive](https://github.com/TheHive-Project/TheHive) are tricky to produce, CyberChef can help now !

Adding Markdown format for To Table operation

---

src/core/config/Categories.json
src/core/operations/RabbitStreamCipher.mjs
tests/operations/index.mjs
tests/operations/tests/RabbitStreamCipher.mjs

fix #1404 
References:
* [RFC4503: A Description of the Rabbit Stream Cipher Algorithm](https://www.ietf.org/rfc/rfc4503.html)
* [Rabbit - Crypto++ Wiki](https://www.cryptopp.com/wiki/Rabbit)

Add new operation: Rabbit Stream Cipher

---

src/web/stylesheets/themes/_dark.css

I noticed, with the diff operation, that the highlight in the dark theme cause the text to be unreadable. I changed the hl3 and hl5 variables to somethink more readable, more dark.

Update dark theme highlight

---

src/core/config/Categories.json
src/core/operations/HKDF.mjs
tests/operations/index.mjs
tests/operations/tests/HKDF.mjs

Add operaton HKDF

---

src/web/html/index.html

Fix loading messages

---

src/core/operations/RegularExpression.mjs

I use this one often so I'm sure others will like it too :)
I've tested it successfully with a local build

Add UUID regex to 'Regular expression' operation

---

src/core/operations/ParseASN1HexString.mjs

Just in case the title of the operation doesn't make it clear enough

Describe that "Parse ASN.1 hex string" operation requires an hex string input

---

.devcontainer/devcontainer.json
.gitattributes

Extended PR #1626 to perform better and sort line endings on Windows
- Add dev container config file
- Add gh-cli, add extensions, node_modules as a volume
----
Also, hello new maintainer! Good to see activity picking up :)

Add devcontainer configuration and .gitattributes

---

src/core/lib/FileSignatures.mjs

File signatures for heic/heif

---

src/core/operations/FromBase58.mjs
src/core/operations/ToBase58.mjs
tests/operations/tests/Base58.mjs

Should fix https://github.com/gchq/CyberChef/issues/1742

Fix Base58 handling of strings with only null characters

---

src/core/operations/SIGABA.mjs

chore: update SIGABA.mjs

---

src/web/App.mjs
src/web/waiters/OptionsWaiter.mjs

Implemented automatic dark theme change based on user preference using the `prefers-color-scheme` media query.

automatically theme mode based on user preference

---

src/core/operations/ROT13.mjs
tests/operations/tests/Rotate.mjs

Fixes https://github.com/gchq/CyberChef/issues/1886.

fix: ROT13 - shifting numbers by negative amounts

---

src/core/operations/ConvertLeetSpeak.mjs
tests/operations/tests/ConvertLeetSpeak.mjs

Preserve uppercase for Leet Speak

---

package-lock.json
package.json
src/core/config/Categories.json
src/core/operations/Jsonata.mjs
tests/operations/index.mjs
tests/operations/tests/Jsonata.mjs

Adds an operation to query and transform JSON data using jsonata
- [jsonata](https://github.com/jsonata-js/jsonata)
Several tests included to exercise jsonata features

feat: add jsonata query operation

---

src/core/operations/GenerateAllChecksums.mjs

Change infoURL for the GenerateAllChecksums operation.

Update GenerateAllChecksums infoURL

---

src/web/static/structuredData.json

Error on load in Safari:
`TypeError: undefined is not an object (evaluating 'r["@context"].toLowerCase')`
Implemented fix described in this stack overflow article: https://stackoverflow.com/a/76998417
Fixes #2036

Workaround for Safari load bug

---

src/core/operations/ExtractEmailAddresses.mjs

Fix email regex
