src/js/config/Categories.js, src/js/config/OperationConfig.js, src/js/operations/NetBIOS.js
Operations to carry out first level encoding and decoding of NetBIOS names, [as per RFC 1001](https://tools.ietf.org/html/rfc1001#section-14.1). Note that the example in the RFC appears to be incorrect.
Comments welcome.
=> 'Encode NetBIOS Name' and 'Decode NetBIOS Name' operations

src/js/config/Categories.js, src/js/config/OperationConfig.js, src/js/operations/Base58.js
For #48
This adds two operations
+ `To Base58`
+ `From Base58`
And includes 2 commonly used Base58 alphabets:
+ Bitcoin
+ Ripple
=> Base58 operations

src/js/operations/Base64.js
This is used by `crypt()` (e.g. in `/etc/shadow`).
(Would be nice to have a `crypt()` ingredient too, since the crypt algorithm is based on applying hashes many times over and is not simple)
http://www.vidarholen.net/contents/blog/?p=32
=> Add crypt base64 format

src/js/core/FlowControl.js, test/tests/operations/FlowControl.js
The return operation was setting `state.progress` to the length of the recipe.
Under async this is incorrect behaviour because after any flow control operation the Recipe executes `state.progress + 1`, and then at the beginning of the recursed `Recipe.execute` checks the length and returns if `currentStep === recipe.opList.length`
Return now sets `state.progress` equal to `state.opList.length - 1`.
This bug could instead have been fixed by changing finish condition from `currentStep === recipe.opList.length` to `currentStep >= recipe.opList.length` to prevent this class of bugs in the future. I'll leave that decision to @n1474335.
Additionally there was a type in the test "Fork, Conditional Jump, Encodings" which was just a missing newline in the input which was required to match the …
=> Fix "Fork, Conditional Jump, Encodings" test and fix the "Return" operation.

src/js/core/Utils.js, src/js/operations/Compress.js
+ Added bytes attribute for "file objects" in untar and unzip
+ Added download button on files displayed by displayFilesAsHTML
+ Fixes bug in "Untar" for binary files.
I was looking to implement PGP detached signatures which outputs a message, an ASCII-armored signature, and a binary file signature.
Looking into the matter further I found there was a bug in the "Untar" operation when reading binary files. The bug caused binary files to get cut off when being read (if they contained a`0` byte). See below
The file displayed is clearly not 218 bytes, it should be:
Also if you wanted to download the contents of that file you would not be able to (some bytes not displayed).
Overall file display now has two buttons
+  `🔍` to show/hide the contents
+ `↴` to download the file
Previously the …
=> Add download button for displayFilesAsHTML files

src/js/operations/Base64.js
I noticed that there was an issue with the "To Base32" operation where it would sometimes miss output characters.
=> Fixed an issue with Base32 encoding

Gruntfile.js, package.json
Added: https://github.com/yargalot/grunt-accessibility
Runs checks over all HTML files in the build folder, thus if you have a dev and a prod build it will report everything twice.
This pull doesn't actually fix any of the accessibility errors/warnings (of which there are about 50).
Once you have something in your "build" folder you can run ```grunt accessibility```
I considered adding the accessibility task as part of the prod build but thought it might be a bit verbose, as a lot of the messages it pumps out are warnings and hints rather than actual errors.
=> add a grunt plugin to check accessibility

src/core/config/OperationConfig.js, src/core/operations/StrUtils.js, test/tests/operations/StrUtils.js
My most common reason to switch out of CyberChef into a terminal is to use `head` or `tail`. The basic functionality of `head` and `tail` is implemented here:
Head operation
+ `head -n 10` => first 10 lines (Number = 10, box = unchecked)
+ `head -n -10` => all lines except the last 10 (Number = 10, box = checked)
+ `tail -n 10` => last 10 lines (Number = 10, box = unchecked)
+ `tail -n +10` => all lines starting from line 10 (Number = 10, box = checked)
You can change the delimiter as needed, so this can even work as a very primitive `cut`:
(I don't recommend this though)
Relevant tests also included.
=> Add Head and Tail operations

src/web/RecipeWaiter.js
Fixed bug where popovers on operations stopped working after the operation was dragged into the recipe.
=> Operation popover bug

src/core/FlowControl.js, src/core/config/Categories.js, src/core/config/OperationConfig.js, test/tests/operations/FlowControl.js
Added 'Comment' operation for annotating the recipe.
In response to #34.
This seemed like the easiest way of adding comments. Another option would be to add an icon to each operation as suggested in #34, however this would require a lot more code.
=> Feature: 'Comment' operation

docs/jsdoc.conf.json, package.json, src/.eslintrc.json, src/core/Chef.js, src/core/FlowControl.js, src/core/Recipe.js, src/core/Utils.js, src/web/App.js, src/web/css/structure/layout.css, src/web/html/index.html, test/TestRegister.js, test/tests/operations/FlowControl.js
This deals with #79 with 11 lines of code changes (and the addition of some tests).
The relevant code changes are exclusively the addition of `async` and `await` where necessary.
This should be able to be dealt with fairly quickly and I can clean up #89 separately.
Summary
+ Async/await to support asynchronous operations
+ Added more tests
+ eslint ecmaVersion changed from 6 to 8
+ Added jsdoc-babel plugin to jsdoc
+ Re-added the UI changes made by n1474335
=> Implement support for async ops.

.travis.yml
This stops Travis from trying to build GH pages for other repos.
I.e. solves [this](https://travis-ci.org/tlwr/CyberChef/builds/234148384) problem.
=> Add repo option to Travis

src/core/operations/SeqUtils.js, test/index.js, test/tests/operations/SeqUtils.js
This allows recipes to sort lists that have numbers logically, e.g.
> photo-8.jpg
> photo-9.jpg
> photo-10.jpg
> photo-11.jpg
Or
> CVE-2017-1234
> CVE-2017-9999
> CVE-2017-10000
> CVE-2017-10001
> CVE-2017-12345
=> Add numeric sorting

src/core/config/OperationConfig.js, src/core/operations/BitwiseOp.js
Adds input and output differential schemes to the `XOR Brute Force` operation. These are already available in `XOR`.
Closes #33.
=> Differential schemes to 'XOR Brute Force' operation

src/core/config/Categories.js, src/core/config/OperationConfig.js, src/core/operations/BCD.js, src/web/html/index.html, test/index.js, test/tests/operations/BCD.js
Added `To BCD` and `From BCD` operations with support for a range of encoding schemes as well as packing and signs.
Closes #49.
=> Binary-Coded Decimal operations

src/web/App.js, src/web/html/index.html, src/web/static/structuredData.json
Added structured JSON data which will allow search engines to understand the application better.
The page title now updates to reflect what is in the recipe. This should make working across multiple tabs a little easier. This could be improved in future.
=> SEO structured data

src/web/HTMLOperation.js, src/web/OperationsWaiter.js, src/web/stylesheets/utils/_overrides.css
Changes data-trigger to focus so scrolling works, sets the max height and enables scrollbar.
Fixes #137.
=> [Fix] Adds scrolling to description popover

src/js/config/Categories.js, src/js/config/OperationConfig.js, src/js/operations/String.js
These operations are useful for taking the contents of a string, and making it
suitable for use as a stand alone string. For example, in an IDE you might see
a string which is represented as: `"Say \"Hello\""`. The escaped double quotes
are shown to make it clear that they do not end the string, despite the fact
that they are not truly part of the string. In order to get the raw string, you
would need to copy this, then manually remove the backslashes. The new
String_.run_unescape operation does this automatically.
The String_.run_escape is the inverse. It allows you to take a string such as 
`Say "Hello"`, and paste it between two quotes without having to manually 
escape it.
The "Parse escaped string" operation is similar, but only operates on new line 
characters. This works on …
=> Add string escape/unescape operations

src/core/operations/Cipher.js
Fixes a bug in the Substitute operation that was preventing commas from being converted correctly.
Discovered when decoding a question asked in the GCHQ Twitter Q&A: https://twitter.com/GCHQ/status/901026153024106497
Solution here: https://gchq.github.io/CyberChef/#recipe=Substitute('SNVFRGHJOKL:%3CMP%7BWTDYIBECUXsnvfrghjokl;,mp%5Bwtdyibecux','ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz')&input=RWpzeSBvZCB1cGl0IGdzYnBpdG95ciBIVkpXIFtpeHg7cj8KU211eWpvbWggZ3RwLCB5anIgW2l4eDtyIG5wcGw
=> Bug fix: Substitute commas

package.json, src/core/config/Categories.js, src/core/config/OperationConfig.js, src/core/operations/OTP.js
Added 'Generate HOTP' and 'Generate TOTP' operations.
Closes #41.
=> OTP operations

src/core/ChefWorker.js, src/core/FlowControl.js, src/core/Recipe.js, src/core/config/Categories.js, src/core/config/OperationConfig.js, src/core/config/modules/Default.js, src/web/RecipeWaiter.js, src/web/WorkerWaiter.js, src/web/stylesheets/components/_operation.css
This PR introduces the 'Register' operation which allows you to extract data from the input and store it in registers which can then be used in subsequent operation arguments.
Multiple registers can be created in a single operation, and multiple register operations can be used together.
This closes #26.
=> Registers - pass input as arguments

.eslintrc.json, src/core/ChefWorker.js, src/core/config/Categories.js, src/core/config/OperationConfig.js, src/core/config/modules/OpModules.js, src/core/config/modules/Shellcode.js, src/core/lib/DisassembleX86-64.js, src/core/operations/ByteRepr.js, src/core/operations/CharEnc.js, src/core/operations/Hexdump.js, src/core/operations/Shellcode.js, src/node/index.js
This PR introduces the 'Shellcode' module, currently comprising of one operation: 'Disassemble x86'.
This operation supports 64-, 32-, and 16-bit code written for Intel or AMD x86 processors.
This closes #68. I initially tried to use [capstone.js](https://github.com/AlexAltea/capstone.js), however its size (5MB minified) caused no end of issues with webpack, so I ended up going with [X86-64-Disassembler-JS](https://github.com/Recoskie/X86-64-Disassembler-JS). In future it would be nice to switch to a more comprehensive library that supports more architectures, but this is a good start while we're waiting for other libraries to mature.
=> Disassemble x86

src/core/operations/SeqUtils.js, test/tests/operations/SeqUtils.js
This PR fixes a small bug in my previous PR #142. Instead of assuming strings that are of different size are equal, the function now relays on a regular string compare.
**Before**
```
Input:
11
9
10
d
b
c
a
Output:
9
11
d
10
b
c
a
```
**After**
```
Input:
11
9
10
d
b
c
a
Output:
a
b
c
d
9
10
11
```
=> BugFix: compare odd size elements, like empty line

src/core/operations/UUID.js
Fixes UUID issue brought up in the [Gitter channel](https://gitter.im/gchq/CyberChef) where the operation had become unusable due to webworkers having no access to the `window` object. UUID operation now uses the native `crypto` package from Node.
=> Bugfix: UUID operation using webworkers

package-lock.json, package.json, src/core/operations/Code.js, test/tests/operations/Code.js
CSS selector operation now works in a web worker. Fixes #218
Using the nwmatcher library along with xmldom because xmldom does not support `querySelectorAll`. The nwmatcher library contains a method called `select` which is roughly functionally equivalent.
=> Fix for CSS selector op

package-lock.json, package.json, src/core/Utils.js, src/core/config/Categories.js, src/core/config/OperationConfig.js, src/core/config/modules/CharEnc.js, src/core/config/modules/Ciphers.js, src/core/operations/Cipher.js, test/tests/operations/Cipher.js
This PR begins to replace [CryptoJS](https://github.com/brix/crypto-js) with [Forge](https://github.com/digitalbazaar/forge). Forge is much better supported and does not contain the many bugs that have been found in CryptoJS.
The following operations make use of CryptoJS but are not supported by Forge. There have been no bug reports raised for them so they will be kept for the moment. In future, they could be replaced by more modern libraries, allowing us to remove CryptoJS entirely.
- RC4
- RC4 Drop
- Derive EVP key
Future possibilities with Forge that won't be addressed in this PR:
- Various RSA operations
- X.509 and ASN.1 support - could replace jsrsasign
This PR currently fixes #58, #63, #210.
=> Replacing CryptoJS with Forge

src/core/Chef.js, src/core/Dish.js, src/web/InputWaiter.js, src/web/Manager.js, src/web/html/index.html, src/web/index.js
Data pasted into the input is treat as a file if it is over the IO length threshold, meaning that it doesn't have to be rendered in the DOM. This vastly improves the performance for large amounts of data.
The default IO threshold has been reduced from 1MiB to 512KiB. This can be adjusted in the options pane.
=> Improve input paste performance

src/core/config/Categories.js, src/core/config/OperationConfig.js, src/core/config/modules/Default.js, src/core/operations/StrUtils.js
This PR adds a new operation: Hamming Distance.
Details can be found here: https://en.wikipedia.org/wiki/Hamming_distance
The operation allows you to specify inputs as a raw string or hex. You can also specify whether you want to measure the distance based on whole bytes, or individual bits.
=> Hamming Distance

src/core/config/OperationConfig.js, src/core/operations/StrUtils.js
This PR realizes the use of "editableOption" for the two parameters of Split;
- Split delimiter
- Join delimiter
The benefit is that a user is free to enter any other delimiters, making Split way more powerful. It can now actually be used to rejoin the input to a different output format.
For example, the input contains items per line and the output show have all items on one line, separated by comma's:
```
Input:
Item1
Item2
Item3
Split delimiter: \n
Join delimiter: , (<comma><space>)
Output:
Item1, Item2, Item3
```
Before it was not possible to use multiple characters as Join delimiter. Additionally some suggestions for the Split delimiter are offered.
=> Make Split more flexible so it can be used to join

src/core/Utils.js, src/core/config/OperationConfig.js, src/core/operations/Hash.js, test/tests/operations/Hash.js
The hashing operations were causing various bugs in certain circumstances.
Tests have been added for the following input types:
- Plain ASCII text
- Complex binary input
- UTF-8 text
Expected test results were generated using Python3.6 hashlib.
Hashing operations now all take input as an ArrayBuffer and decode strings as UTF-8 by default. Binary input is handled correctly. All tests currently pass.
Closes #249.
=> BUGFIX: UTF-8 handling in hashing operations

.babelrc, package-lock.json, package.json, src/core/Recipe.mjs, src/core/errors/OperationError.mjs, src/core/operations/CartesianProduct.mjs, src/core/operations/SetDifference.mjs, src/core/operations/SetIntersection.mjs, src/core/operations/SetUnion.mjs, src/core/operations/SymmetricDifference.mjs
Add `OperationError` Error type and use for errors to be printed to the output panel
In issue #287 I mentioned error handling behaviour and the need for Operations to throw errors. This is so in the api we can catch them and return them in the expected format (in a promise `.catch`, for example).
This PR lays the ground work for that by introducing an `OperationError` class, which is thrown whenever an operation caught an error and printed the message as the output. The Recipe now handles the error catching and printing, but only if it is of this new `OperationError` class.
There was enough work here for it to be a standalone PR. Plus, I think it's best to introduce this error class ASAP so we can use it in the other operations as we move them over to module format. I have converted all …
=> Add OperationError error type

src/core/config/Categories.js, src/core/config/OperationConfig.js, src/core/config/modules/Default.js, src/core/operations/ToTable.js
This attempts to resolve #275 
This will be my first contribution to CyberChef so open to any feedback or corrections if I've missed anything.
Also, after starting work on this I noticed the ESM rewrite that's currently underway. Obviously, I'm happy for this PR to be ignored until that's complete and I can update it to work with the new system as required.
Screenshot of the new operation:
=> Added ToTable operation to output data as ASCII or HTML tables.

src/core/config/Categories.json, src/core/operations/HaversineDistance.mjs, test/index.mjs, test/tests/operations/HaversineDistance.mjs
This operation calculates the great circle distance between two GPS co-ordinates, returning the value in metres. It includes accompanying test and categorization.
=> Haversine distance operation

src/core/config/Categories.json, src/core/config/scripts/portOperation.mjs, src/core/operations/DechunkHTTP.mjs, src/core/operations/legacy/HTTP.js
This decoder will join up a HTTP response sent using chunked transfer encoding, raised in issue #168.
This is useful when attempting to extract files or gzipped responses sent using chunked transfer encoding, particularly when combined with the gunzip operation.
Resubmitted this PR to the esm branch - Please let me know if I've made any errors.
GCHQ OSS Contributor License Agreement has been signed.
=> Added decoder for chunked HTTP encoding

src/core/config/Categories.json, src/core/lib/Base85.mjs, src/core/operations/FromBase85.mjs, src/core/operations/ToBase85.mjs
To resolve #286.
This adds two new operations:
- To Base85
- From Base85
Both operations include three common alphabets for Base85:
- Standard - also known as Ascii85, and is the standard alphabet for base85.
- Z85 (ZeroMQ) - a "string safe" variant which doesn't use single or double quotes, backslashes, or other problematic characters.
- IPv6 - alphabet used for encoding IPv6 addresses, as defined by RFC 1924.
The "To Base85" operation also has an "Include delimiter" option, which will add `<~ `and `~>` at the start and end of the output, which is a standard used in Adobe PostScript.
=> Added Base85 operations (new)

src/core/operations/Whirlpool.mjs
Fixed typo in operation description.
Wirlpool -> Whirlpool
=> Fixed typo

package.json, src/core/config/Categories.json, src/core/operations/JWTDecode.mjs, src/core/operations/JWTSign.mjs, src/core/operations/JWTVerify.mjs, test/index.mjs, test/tests/operations/JWTDecode.mjs, test/tests/operations/JWTSign.mjs, test/tests/operations/JWTVerify.mjs
Having some trouble designing tests for these, due to the creation of an `iat` token within the JSON response that represents the time that the token was created at.  Ideas are welcome.
=> Add JWT Verify, Decode and Sign Operators

src/core/Utils.mjs
Fixes #375.
This just removes the logic to ignore backslashes and only render the next character, which seems to work as expected.
=> Stop treating backslashes in CSV as escape character

src/web/HTMLOperation.mjs
Fixes #368.
This checks for `wikipedia.org` in the URL rather than just `wiki`, which was catching the GitHub wiki pages as well.
=> Make the check for Wikipedia URLs slightly stricter

src/web/stylesheets/components/_operation.css
Occasionally depending on the page width and the operation used, the label.bmd-label-floating's wraps and covers the input - CSS to hide the wrap
On register-list, if the regex match is not words (spaces that can be wrapped) and longer than the div, it'll overrun - added CSS of word-break: break-all
=> CSS label / register-list Aesthetics

.babelrc, src/core/operations/FromBase58.mjs, src/core/operations/Scrypt.mjs, src/core/operations/ToBase58.mjs, test/tests/operations/Base58.mjs
This should hopefully fix a few issues:
Static file loading issues: #388, #395, #393 (I also am not experiencing a #402 CharEnc issue with this build but I am not sure if this is a fix for this issue)
Scrypt using string for salt: #401 
Base58 converting \x00 at begining and ending incorrectly: #380
=> Fixing the babel, scrypt, and base58 issues

src/core/operations/HMAC.mjs, test/tests/operations/Hash.mjs
Use toggleString for Key in HMAC as proposed in #263. This makes HMAC additionally support keys formatted as:
- Hex
- Decimal
- Base64
- UTF-8
HMAC will produce the same results as before when using `Latin1`:
```
Input: asdffa
Old recipe: HMAC('01020304€','MD5')
New recipe: HMAC({'option':'Latin1','string':'01020304€'},'MD5')
Output: 4f0fa244b0dd2f9c257abc906bdf2a7a
```
=> Use toggleString for Key in HMAC

src/core/operations/Sort.mjs, test/tests/operations/SeqUtils.mjs
This PR adds support for hexadecimal values to the sorting module.
Example input:
```
06
08
0a
0d
0f
1
10
11
12
13
14
15
16
17
18
19
1a
1b
1c
1d
1e
1f
2
3
4
5
7
9
b
c
e
```
Expected output:
```
1
2
3
4
5
06
7
08
9
0a
b
c
0d
e
0f
10
11
12
13
14
15
16
17
18
19
1a
1b
1c
1d
1e
1f
```
=> Support hexadecimal in numeric sort

src/core/config/Categories.json, src/core/operations/DecodeCitrixCTX1.mjs, src/core/operations/EncodeCitrixCTX1.mjs, test/tests/operations/Ciphers.mjs
This should add the requested operation for Citrix CTX1 encoded passwords in issue #413.
=> Citrix CTX1 Encoding/Decoding

src/core/operations/JSONBeautify.mjs, test/index.mjs, test/tests/operations/JSONBeautify.mjs, test/tests/operations/JSONMinify.mjs
Adding capability to sort the key names of javascript objects when displayed as JSON. This resolves #411.
=> Json object sort

src/core/operations/HMAC.mjs, test/tests/operations/Hash.mjs
=> Fix HMAC operation when hex key has bytes >= 0x80 (#437)

src/core/config/Categories.json, src/core/operations/FromBase62.mjs, src/core/operations/ToBase62.mjs, test/index.mjs, test/tests/operations/Base62.mjs
Hi,
I added the "To Base62" and "From Base62" operations. These two operations should function the same as [base62.io](https://base62.io/).
=> Add "To Base62" and "From Base62" operations

src/core/config/Categories.json, src/core/operations/TextEncodingBruteForce.mjs, test/index.mjs, test/tests/operations/TextEncodingBruteForce.mjs
Closes #423.
Made a simple operation that just runs through all the charsets and encodes the input with each. Added a test for it as well.
=> Add Text Encoding Brute Force operation

src/core/config/Categories.json, src/core/lib/LoremIpsum.mjs, src/core/operations/LoremIpsumGenerator.mjs
To resolve: https://github.com/gchq/CyberChef/issues/421
Lorem Ipsum placeholder text can be generated at different lengths, based on: paragraph, sentence, work or byte length.
The text always begins with Lorem ipsum dolor sit amet so that it is easily recognisable.
i haven't written an tests for this operation as im not sure how to test the randomly generated outputs.
=> add lorem ipsum generator

src/core/config/Categories.json, src/core/operations/FromCaseInsensitiveRegex.mjs, src/core/operations/ToCaseInsensitiveRegex.mjs, test/index.mjs, test/tests/operations/ToFromInsensitiveRegex.mjs
Just a small utility I personally find useful. I sometimes deal with regexes that can't use flags such as /i or \c to make them case-insensitive, so I often need to transform them to regexes that _are_ case-insensitive, and doing so by hand is tedious and awful. Usually I'm working with a regex that is a fairly straightforward string though... for example,
Case-sensitive:
```
Mozilla/[0-9].[0-9] .*
```
Case-insensitive:
```
[mM][oO][zZ][iI][lL][lL][aA]/[0-9].[0-9] .*
```
I haven't really needed to work with crazier regexes, so it might be a kinda fragile operation, but it gets the job done for my purposes, hoping others get use out of it too. Suggestions welcome!
=> To/From Insensitive Regex Operations

src/core/config/Categories.json, src/core/operations/Subsection.mjs
Add a new flow control operation to operate only on a section of the input data (#427 ). 
This operation works in a similar way to Fork, running all subsequent operations on the input subsection until a Merge is reached.
=> Subsection operation

src/core/lib/ConvertCoordinates.mjs
Small change to fix the Convert co-ordinate format operation when using just the compass directions as delimiters for the input.
=> Bug Fix: Fix conversion when using compass directions as input delimiters

src/core/config/Categories.json, src/core/operations/DNSOverHTTPS.mjs
Pull request to implement #433. 
Takes a domain name as input, before performing a fetch request to the specified resolver. If only the answer data is needed, an option to just return a JSON array of values is implemented. 
~~It is worth noting that I have put this is the "code" module as I noticed that _jsonpath_ library is used by the [jpath](https://github.com/gchq/CyberChef/blob/master/src/core/operations/JPathExpression.mjs) recipe. It is also used in this recipe to implement the feature of only returning answer data rather than the full JSON response. I'm new to the CyberChef codebase so please let me know if there is a better way of doing this!~~
EDIT: I have now removed the _jsonpath_ import and moved to the "Default" module.
Example Outputs:
=> Operation: DNS Over HTTPS

src/core/vendor/DisassembleX86-64.mjs
Update to disassembler to fix jump addresses ([issue](https://github.com/Recoskie/X86-64-Disassembler-JS/issues/6) from upstream). Also added license information and author accreditation.
Thanks to @JohnLaTwC for flagging this up on [Twitter](https://twitter.com/JohnLaTwC/status/1104539516038045697).
Addtionally, at some point we should update this operation to use something like [zydis](https://github.com/zyantific/zydis) with WASM but I'll have to do more research before I commit to doing that. :stuck_out_tongue:
=> Update disassembler library

src/core/operations/XPathExpression.mjs
References https://github.com/gchq/CyberChef/issues/495
Modified xpath select call to support the allowAnyNamespaceForNoPrefix flag which will allow using prefix-less node tests to match nodes with no prefix.
=> Bug Fix: Added support for non-prefixed default namespace xpath expression

package-lock.json, package.json, src/core/config/Categories.json, src/core/operations/BLAKE2b.mjs, src/core/operations/BLAKE2s.mjs, src/core/operations/GenerateAllHashes.mjs, tests/operations/index.mjs, tests/operations/tests/BLAKE2b.mjs, tests/operations/tests/BLAKE2s.mjs
A pull request to implement #523.
Still to do:
Example:
=> Operation: BLAKE2 hashing functions

src/core/Dish.mjs
A new Dish with no arguments will now construct a zero-length ArrayBuffer.
This will make an empty dish consistent with the new base type of ArrayBuffer.
=> change empty Dish initialisation to use ArrayBuffer

.travis.yml
Since node.js v 12.0.0 was released it was picked up by travis and builds are now failing due to some nasty compiler issues with node-sass. Fix node version to use LTS rather than latest.
=> configure travis to use node LTS instead of latest

src/web/RecipeWaiter.mjs
When you drag an operation from the menu right back into the menu again, the popover disappears when  hovering over it. See the following gif for details:
This PR fixes this issue by recreating the popover on the original item itself, if no clone parent is found.
=> Bug Fix: Disappearing Popover

src/core/config/Categories.json, src/core/operations/IndexOfCoincidence.mjs, tests/operations/index.mjs, tests/operations/tests/IndexOfCoincidence.mjs
This PR adds the Index of Coincidence operation, which calculates the IC of any given text (see [here](https://en.wikipedia.org/wiki/Index_of_coincidence)).  
This acts as a kind of mix between entropy and frequency analysis, and is often used to automatically determine whether ciphers are decoded.
You can see an example output [here](https://user-images.githubusercontent.com/16269580/59152299-fa151c80-8a38-11e9-89c7-6c1a82535d0c.png).  
I capped the graph output at 0.25, as otherwise the data is almost always crammed in the first quarter.
=> Operation: Index of Coincidence

src/core/Utils.mjs, src/core/operations/UnescapeString.mjs
This makes sequences like `\170` unescape to `x`. It would be useful for embedded data in C headers or certain Go log output.
=> Parse octal escape sequences

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/operation-request.md
When browsing the project I noticed the following message when viewing the [issue_template.md](https://github.com/gchq/CyberChef/blob/master/.github/ISSUE_TEMPLATE.md) file. 
More details on issue templates can be found [here](https://help.github.com/en/articles/about-issue-and-pull-request-templates).
- Updated to have predefined issue templates for the following:
- Bug Reports
- Operation Requests
- Feature Requests
- The default issue template now has no suggested layout, however does have a comment asking for 'Misc: ' to be used in the title. 
- The feature and bug reports are the standard GitHub suggested templates with the following small changes and may wish to be customized further.
- Bug Report:
- Suggests adding a link to the recipe / input used to cause the bug under `To …
=> Misc: Updated issues to use issue templates

src/core/operations/PGPDecryptAndVerify.mjs, src/core/operations/PGPVerify.mjs, tests/operations/tests/PGP.mjs
Additionally added some more metadata to PGP Decrypt and Verify operation.
Fixes #581.
=> Added PGP verify operation

src/core/config/Categories.json, src/core/operations/CRC8Checksum.mjs, tests/operations/tests/Checksum.mjs
Addresses https://github.com/gchq/CyberChef/issues/543
Calculates the CRC-8 checksum for a given input. Allows the user to select a checksum algorithm from a drop down.
=> Feature: Added CRC-8 Checksum

src/core/config/Categories.json, src/core/operations/DefangIP.mjs, tests/operations/index.mjs, tests/operations/tests/DefangIP.mjs
A pull request to implement #553.
**Example**:
**Todo:**
=> Operation: Defang IP

CHANGELOG.md, src/web/App.mjs, src/web/Manager.mjs, src/web/html/index.html, src/web/index.js, src/web/waiters/InputWaiter.mjs, src/web/waiters/OptionsWaiter.mjs, src/web/waiters/OutputWaiter.mjs, src/web/workers/InputWorker.mjs
A few fixes and improvements:
- Switching wasn't working properly, so now it should behave as intended (only creating overlays when the input is not a string, too big, or contains carriage returns (see below), and actually autobaking when it should)
- I've added an option for whether or not to preserve carriage returns in the input. (HTML textareas don't support them). When this option is enabled, any inputs containing carriage returns is stored as an ArrayBuffer instead of text, but the user will not be able to edit the input.
- The first time a carriage return is detected, the user gets asked for their preference.
- They then get alerted each time a CR is detected what the app is doing, either that editing is being turned off or their carriage returns will be lost
- The nicer looking …
=> Bug Fix: Switching output to input and carriage returns

src/core/config/Categories.json, src/core/operations/ParseUDP.mjs, tests/operations/index.mjs, tests/operations/tests/ParseUDP.mjs
Added a basic operation to parse a UDP packet and extract the Source Port, Destination Port, Checksum and Length, as well as any data if present. 
Features:
- Outputs JSON allowing for easy chaining of operations (demonstrated in the last screenshot)
- Renders output into a HTML table if the last operation
_Please ignore the spelling of "destination" in these screenshots, it is not present in the PR_
=> Operation: Parse UDP

src/core/operations/ScanForEmbeddedFiles.mjs
Change "suffiently" to "sufficiently"
=> Fix typo in ScanForEmbeddedFiles

src/core/operations/ChangeIPFormat.mjs, tests/operations/index.mjs, tests/operations/tests/ChangeIPFormat.mjs
I couldn't see any tests for the existing functionality so I've added some that ensure each of the four input and output formats is tested once.
The logic for octal and decimal is very similar so I've pulled some of it out into a separate method to save duplicating all the bit-fiddling.
=> Feature: Add octal support to Change IP Format.

src/core/config/Categories.json, src/core/lib/Bacon.mjs, src/core/operations/BaconCipherDecode.mjs, src/core/operations/BaconCipherEncode.mjs, tests/operations/index.mjs, tests/operations/tests/BaconCipher.mjs
This PR adds encoding and decoding for Bacon Cipher in different variations.
For decoding:
You can choose between the reduced (original) alphabet (where I=J and U=V) and the complete 26 character alphabet.
You can choose which letter translation to code to use:
- _0/1_ only treats 0 and 1 and ignores everything else
- _A/B_ only treats A, a, B, b and ignores everything else
- _Case_ treats all 26 standard characters and calculates code based on uppercase/lowercase
- _A-M/N-Z_ treats all first letters of each word
Additionally there's the option to invert the translation.
For encoding:
You can only choose between _0/1_ and _A/B_ translation and the inverse.
In addition to that you can specify whether you want to keep special characters like whitespace or punctuation.
=> Add Bacon cipher operation

package-lock.json, package.json, src/core/config/Categories.json, src/core/operations/OCR.mjs
Addresses https://github.com/gchq/CyberChef/issues/628
Utilizes https://github.com/naptha/tesseract.js to perform OCR on images.
=> Feature: OCR

package-lock.json, package.json, tests/node/tests/operations.mjs, tests/operations/tests/Crypt.mjs
Background: https://github.com/gchq/CyberChef/pull/647
This PR updates forge version to 0.9.1 to correct DES and 3DES CTR modes' outputs. forge 0.9.1 also enforces IV size to be the same as the cipher's block size. This PR updates the tests in which IVs are absent or are not the correct size.
The ground truths of tests for DES-CTR and DES-EDE3-CTR modes appear to have been generated by previous versions of forge, and are therefore incorrect. This PR corrects them using the results from GoLang's standard library and pyCryptoDome
=> Update forge version to 0.9.1 to correct DES and 3DES CTR mode results, and update tests

package-lock.json, src/node/NodeRecipe.mjs, tests/node/tests/nodeApi.mjs
With this change, `bake` can handle recipes where an `op` property is set, but no `args` property is. This is helpful for when we want to POST configs over some RESTful API, but don't need to explicitly define each argument.
Missing arguments fall back to their defaults, as is the case when just the operation is defined.
This sample input to bake is now valid:
``` javascript
[
{ "op": "To Morse Code" }, // no "args" property, so recipe will fall back to default args here
{ "op": "Hex to PEM",
"args": ["SOMETHING"] },
{ "op": "To Snake case",
"args": [false] }
]
```
=> Update NodeRecipe so args is optional in bake config

src/core/operations/Bzip2Decompress.mjs, src/core/operations/GeneratePGPKeyPair.mjs, tests/lib/TestRegister.mjs, tests/node/assertionHandler.mjs, tests/node/tests/operations.mjs
Any node test which was `async` was not failing when it should have.
The wrapper for the node tests to fit into the `TestRegister` was not respecting the potentially async nature of the call and not catching the Exception.
Updated some tests which were failing - mostly encryption related where different values are generated on each pass. Two operations needed `async` to be added to their `run` signatures - The Node wrapper for operations relies on this to figure out if they're async or not.
Thanks @mattnotmitt for spotting this.
=> Bugfix: Make async node tests actually fail when they fail.

src/core/Utils.mjs
fixes #589
This removes the special logic for understanding three backslashes in a row as an escaped single backslash.
=> Utils: don't consume three backslashes at a time

src/core/operations/PHPDeserialize.mjs
PHP Deserialize now returns proper null value for a value of N in PHP serialized data.
Closes #641
=> PHP Deserialize return null for N

README.md, src/web/App.mjs
I added a `theme` parameter to the query string that overrides the user's theme.
I made it override rather than only take effect by default because if a page with a dark theme is trying to embed a cyberchef window, it would be jarring if the cyberchef frame had a light theme.
A better balance may be to make the `theme` parameter only accept `light` or `dark`. If the user's preferred theme is light and the `theme` parameter is `light`, then the user's theme will be used. Otherwise, the theme will be set to some dark theme.
Fixes #594.
=> Theme configuration through url

src/core/operations/Diff.mjs, tests/operations/tests/StrUtils.mjs
Adds "Show Subtraction" button to allow seeing only the difference
between two texts.
When selected and combined, user can see only the characters or
words that were added. If not combined, with either removed or added
but selected, then nothing is displayed.
=> diff.mjs: Allows showing subtraction

src/core/operations/BaconCipherDecode.mjs, src/core/operations/BaconCipherEncode.mjs, src/core/operations/DefangIPAddresses.mjs, src/core/operations/ParseSSHHostKey.mjs
While this doesn't solve the upstream import's which don't comply to the mandatory file extensions it preps CyberChef for it.
=> Add file extensions which are mandatory for the latest Node 12.x.

src/core/lib/FileSignatures.mjs
Instead of seeking forward to a value, I jump forward by the specified amount.
=> Made GIF extractor more robust.

src/core/lib/FileSignatures.mjs
EVT, EVTX, SQLITE extractors. 
Extra signatures which include shebangs for python, perl, bash/sh and Ruby.
=> Extractors for EVT, EVTX, SQLITE added along with some extra signatures.

.eslintrc.json, src/core/lib/FileSignatures.mjs, src/core/lib/Stream.mjs
continueUntil now uses the Boyer-moore string search algorithm. 
consumeWhile consumes bytes while the byte is equal to the given value.
EVTX extractor can now extract all of the file, thanks to consumeWhile.
=> Improved continueUntil, added consumeWhile and made the EVTX extractor more complete

src/core/lib/Base85.mjs
According to python3 base64.b85decode module https://github.com/python/cpython/blob/3.8/Lib/base64.py
=> Fixed typo in IPV6 alphabet

src/core/operations/DNSOverHTTPS.mjs
This argument sets the "cd" parameter on the request.
For both included providers, this flag disables validation ([1], [2]), so doing the exact opposite of the described action.
This changes the label to the correct name and also flips the default value to keep the old behavior.
[1] Google <https://developers.google.com/speed/public-dns/docs/doh/json#supported_parameters>
[2] Cloudflare <https://developers.cloudflare.com/1.1.1.1/dns-over-https/json-format/>
=> DNS over HTTP: Fix "validate" argument

src/core/lib/FileSignatures.mjs
Certain RTF files may attempt to thwart detection by having a malformed RTF header, such as **{\rt000**. Removing 0x66 will result in detecting these malformed yet valid RTFs as well.
Additional reading:
https://www.decalage.info/rtf_tricks#Trick_1:_Incomplete_RTF_Header
=> Improve RTF detection

src/core/lib/FileSignatures.mjs, src/core/operations/ToCaseInsensitiveRegex.mjs, tests/operations/tests/ToFromInsensitiveRegex.mjs
Originally the ToCaseInsensitiveRegex operation on input [A-Z] would produce [[aA]-[zZ]] which is not the correct result.
I have added a few more rules and modified the original rule to allow this input and more.
=> To Case Insensitive Regex Operation improved.

package-lock.json, package.json, src/core/config/Categories.json, src/core/lib/ChrEnc.mjs, src/core/operations/NormaliseUnicode.mjs, tests/operations/index.mjs, tests/operations/tests/NormaliseUnicode.mjs
See #872
I made a mistake while signing the CLA. My email should be "m[at]tthieu.xyz" instead of "m[at]tthieu". I don't know how to fix that...
=> Add operation to normalise unicode

Gruntfile.js
Currently there is no way to run CyberChef on a custom port, i.e. other than 8000/8080. This change allows you to specify `--port=1234` when running `grunt dev` or `npm run start -- --port=1234`.
Source: https://github.com/gruntjs/grunt/issues/534
=> Allow custom ports for Grunt dev task

src/core/config/Categories.json, src/core/operations/RailFenceCipherDecode.mjs, src/core/operations/RailFenceCipherEncode.mjs, tests/operations/tests/Ciphers.mjs
Recently while taking part in a CTF I had to use the Rail Fence Cipher. I've realized my favourite tool (yes it is CyberChef) didn't have it so I decided to contribute it.
The cipher itself is quite simple. For more infos https://en.wikipedia.org/wiki/Rail_fence_cipher or check this site where you can visualize the cipher in action http://rumkin.com/tools/cipher/railfence.php
=> Rail Fence Cipher with both encoding and decoding

src/core/config/Categories.json, src/core/operations/LuhnChecksum.mjs, tests/operations/index.mjs, tests/operations/tests/LuhnChecksum.mjs
Luhn Checksum Operation added.
Generates the check-digit for the Luhn Algorithm. 
#963
=> Luhn Checksum Operation Added

src/core/config/Categories.json, src/core/operations/GenerateImage.mjs
This is a new operation which takes a byte array, and creates an image from it.
Supported modes:
* Grayscale  (every byte is a pixel)
* RG  (two bytes represent a pixel)
* RGB  (three bytes represent a pixel)
* RGAB  (four bytes represent a pixel (alpha-channel))
* Bits (every bit represents a pixel)
---
*Example where we import a BMP and interpret it bytewise:*
*Example where ABCDEFGHIJKLMNOP is shown as Bits*
=> New Operation: Generate Image

src/web/waiters/RecipeWaiter.mjs
Currently, operations in Recipe section have descending z-indices, so that dropdown menus from an operation above doesn't get covered by the operations below it:
But when the menu becomes a "dropup" menu, all its items are covered by operations above it:
This pull request removes the z-index setter, and the menu appears correctly as the topmost element in both cases.
=> Correct stack order of dropup menus

src/core/config/Categories.json, src/core/operations/ParseObjectIdTimestamp.mjs, tests/operations/index.mjs, tests/operations/tests/ParseObjectIdTimestamp.mjs
This PR adds a new operation to parse the timestamp from [MongoDB ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/) hex strings.
=> Add ObjectId timestamp parser operation

src/core/lib/FileSignatures.mjs, src/core/lib/Stream.mjs
Extractor and signature added for Targa images.
Does things in a sightly unorthodox fashion since it parses up the file opposed to down.
=> Targa extractor

Gruntfile.js
This threw me off for a few minutes. The Gruntfile says `npm tests` will run the tests but it is actually implemented as `npm test`.
=> Grunt npm tests changed to npm test

src/core/operations/NormaliseUnicode.mjs, tests/operations/tests/NormaliseUnicode.mjs
Simple bug fix.
Related: #872 #912
=> Fix bug in Normalise Unicode operation: replace nfc by nfkc

src/node/NodeRecipe.mjs, src/node/api.mjs, src/node/config/scripts/generateNodeIndex.mjs, tests/lib/TestRegister.mjs, tests/node/tests/nodeApi.mjs, tests/node/tests/operations.mjs
This change makes the node API handle flowControl operations, in particular it will allow people to run the Magic operation in the Node API.
This is a cleaner PR than #958 where I made a mess of rebasing.
=> Allow magic in node api

src/core/operations/CTPH.mjs, src/core/operations/CompareCTPHHashes.mjs, src/core/operations/CompareSSDEEPHashes.mjs, src/core/operations/ExtractFiles.mjs, src/core/operations/SSDEEP.mjs
Updating the links to the ForensicsWiki website as forensicswiki.org has moved to forensicswiki.xyz.
=> Updated the links to forensic wiki website

src/core/operations/WindowsFiletimeToUNIXTimestamp.mjs
closes #1090 
I opted for a "Swap Endianness" argument over an explicit input endianness argument.
=> Convert to/from FILETIME does not handle little endian hexadecimal

.nvmrc, .travis.yml
avoids storing node version in travis to allow nvm tool for local dev
=> use nvmrc file

src/core/operations/RailFenceCipherDecode.mjs
The rail fence decode algorithm works without padding. Adding padding incorrectly decrypts strings. See #1069
=> Don't pad rail fence decode fixes #1069

src/core/config/Categories.json, src/core/operations/HAS160.mjs, src/core/operations/MD2.mjs, src/core/operations/SHA0.mjs, src/core/operations/SHA1.mjs, src/core/operations/SHA2.mjs, src/core/operations/SM3.mjs
In the crypto-api library there is an options structure for hashing algorithms that allows a different number of rounds to be performed. Contained in this PR is arguments added to the relevant operations.
=> Option structures added for hashing algorithms

src/core/operations/Colossus.mjs, src/core/operations/ExtractDomains.mjs, src/core/operations/ExtractFiles.mjs, src/core/operations/FrequencyDistribution.mjs, src/core/operations/Lorenz.mjs
I noticed in `OperationConfig.json` that some boolean arguments didn't look right
=> Use proper booleans instead of relying on truthy/falsy values

src/core/lib/JWT.mjs, src/core/operations/JWTSign.mjs, src/core/operations/JWTVerify.mjs
Fixes #1073 - issue with JWT verify not working
The issue stemmed from the fact the list of signing algorithms did not match the list of algorithms that could be verified. This meant that you could created a recipe that signed something and then verified it, and it would fail for some signing algorithms.
The fix creates a new file with the list of JWT algorithms that can be used, and the two operations use that instead.
=> JWT Algorithms file to fix JWT sign/verify inconsistency

src/core/operations/FrequencyDistribution.mjs
When showing results in the frequency distribution table, it's quite
helpful to see the distribution of the ASCII letters, if any. Provide an
option to show this to show the characters alongside the code.
Fixes #1169.
Signed-off-by: Alex Blewitt <alex.blewitt@gmail.com>
=> Add ASCII output for frequency table

src/core/config/Categories.json, src/core/operations/ExtractID3.mjs
I have added an Extractor/Viewer for ID3 Tags inside MP3 files. ID3 is the metadata format for newer mp3 files.
Closes #915
=> ID3 Extractor

src/core/config/Categories.json, src/core/operations/GenerateCurrentEpoch.mjs
As far as I can tell, I cannot extended the granularity to microseconds.
closes #1044
=> Generate Epoch Time Operation Added

package-lock.json, package.json, src/core/config/Categories.json, src/core/operations/CBORDecode.mjs, src/core/operations/CBOREncode.mjs, tests/operations/index.mjs, tests/operations/tests/CBORDecode.mjs, tests/operations/tests/CBOREncode.mjs
Implementation for #991 
Requires #998 to be merged first for all tests to pass
=> Issue 991 - CBOR operations

src/core/config/Categories.json, src/core/operations/GetAllCasings.mjs, tests/operations/index.mjs, tests/operations/tests/GetAllCasings.mjs
=> All Case Variations Of String

src/core/Utils.mjs, src/core/config/Categories.json, src/core/lib/Base45.mjs, src/core/operations/FromBase45.mjs, src/core/operations/ToBase45.mjs, tests/operations/index.mjs, tests/operations/tests/Base45.mjs
=> Add Base45 operations

src/core/operations/GetAllCasings.mjs, tests/operations/tests/GetAllCasings.mjs
https://github.com/gchq/CyberChef/pull/1065
=>  fix: GetAllCasings.mjs - newline bug

src/core/config/Categories.json, src/core/lib/SM4.mjs, src/core/operations/AESDecrypt.mjs, src/core/operations/DESDecrypt.mjs, src/core/operations/SM4Decrypt.mjs, src/core/operations/SM4Encrypt.mjs, src/core/operations/TripleDESDecrypt.mjs, tests/operations/index.mjs, tests/operations/tests/SM4.mjs
This adds an implementation of the SM4 block cipher, and operations
to encrypt and decrypt using it with CBC,ECB,CFB,OFB,CTR modes.
Also, a "no padding" option is added for AES,DES,3DES and SM4
decryption in ECB/CBC modes. This variant does not attempt to
validate the last block as being PKCS#7 padded.
This is useful, both since other padding schemes exist, and also
for decrypting data where the final block is missing or corrupted.
Adds no new external dependencies.
=> Add the SM4 block cipher, also a no-padding option for decrypting block ciphers.

src/core/lib/Binary.mjs, src/core/operations/ToUpperCase.mjs
In ``Binary.mjs`` the examples for ``toBinary`` and ``fromBinary`` seem to have incorrect return values.
In the ``toBinary`` function, I've added replaced the ``return ""`` with an exception to make debugging clearer.
The ``ToUpperCase`` operation has been restructured so that each scope (e.g "Word", "Sentence", "Paragraph") has its regex contained within a dictionary, this should make extending the functionality/modifying individual regular expressions easier (and exception-throwing has been added in the instance of an invalid scope being provided).
=> Minor comment/formatting improvements

src/core/operations/PEMToHex.mjs, tests/operations/index.mjs, tests/operations/tests/PEMtoHex.mjs
previous implementation only supported some PEMs (e.g. Certificate)
the new implementation is more general,
it just extracts the base64 between
header and footer and decodes that to hex
=> PEMtoHex: Support arbitrary PEMs

src/core/config/Categories.json, src/core/lib/Stream.mjs, src/core/operations/ELFInfo.mjs, tests/operations/index.mjs, tests/operations/tests/ELFInfo.mjs, tests/samples/Executables.mjs
The code in this PR implements readelf-like functionality into CyberChef. It utilises the stream library for most of it's processing and I have attempted to make it agnostic between 32-bit and 64-bit.
I have tested it on both 32-bit and 64-bit ELF files.
The tests are pretty thin on the ground for this one but I could create a small, totally invalid, ELF to use.
=> Implemented readelf-like functionality.

src/core/config/Categories.json, src/core/operations/PLISTViewer.mjs
Added an operation to display a plist file in a more readable format.
=> Plist viewer

src/core/config/Categories.json, src/core/operations/CaesarBoxCipher.mjs, tests/operations/index.mjs, tests/operations/tests/CaesarBoxCipher.mjs
=> Caesar Box Cipher Added

src/core/config/Categories.json, src/core/operations/ROT8000.mjs, tests/browser/ops.js, tests/operations/tests/Rotate.mjs
The simple Caesar-cypher encryption that replaces each Unicode
character with the one 0x8000 places forward or back along the
alphabet.
[https://github.com/rottytooth/rot8000](https://github.com/rottytooth/rot8000)
[https://www.schneier.com/blog/archives/2021/09/rot8000.html](https://www.schneier.com/blog/archives/2021/09/rot8000.html)
=> Add ROT8000

package-lock.json, package.json, src/core/config/Categories.json, src/core/operations/LZMACompress.mjs, src/core/operations/LZMADecompress.mjs, tests/operations/tests/Compress.mjs
I used a [fork](https://github.com/blu3r4y/LZMA-JS) of LZMA-JS which had ES6 import support. 
Closes #1417.
=> Add LZMA Compress & Decompress operations

src/core/operations/RawInflate.mjs
This situation occurs because the dependancy (zlibjs/bin/rawinflate.min.js) doesn't do a sanity check on distances going back farther than the current buffer.
For example:
DEFLATE data of '123' and then a length of 9 going back a distance of 6
ASCIIHEX: 333432869300
! infgen 3.0 output
!
last			! 1
fixed			! 01
literal '1		! 10000110
literal '2		! 01000110
literal '3		! 11000110
match 9 6		! 1 00100 1110000
infgen warning: distance too far back (6/3)
end			! 0000000
! 0
We only have 3 characters, we shouldn't be able to seek 6 characters back. But rawinflate.min.js doesn't check for this like the infgen debug tool (and others) would. So CyberChef would happily provide this as the result:
123...123...
Where the dots are just nulls of likley empty memory preceding the actual buffer
So with …
=> Removal of unnecessary error condition

.github/workflows/codeql.yml, .github/workflows/master.yml, .github/workflows/pull_requests.yml, .github/workflows/releases.yml
This PR bumps GitHub Actions to their latest major versions, which now use Node 16 internally instead of Node 12 (EOL as of end of April 2022, no longer receives security updates):
-   Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
-   Changelog for `crazy-max/ghaction-github-pages` can be [found here](https://github.com/crazy-max/ghaction-github-pages/blob/dev/CHANGELOG.md)
-   Changelog for `github/codeql-action` actions can be [found here](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
=> Update GitHub Actions

src/core/config/Categories.json, src/core/operations/NTLM.mjs, tests/operations/index.mjs, tests/operations/tests/NTLM.mjs
I often found myself using online tools for getting NTLM hashes while working with Windows networks or doing sandboxes like HackTheBox. It would be nice to have it as one operation in CyberChef, so I implemented it.
It performs MD4 on UTF16LE-encoded input and makes it uppercase because that's how it appears most often.
=> Added NTLM operation

src/core/operations/PseudoRandomNumberGenerator.mjs
Current "Pseudo-Random Number Generator" operation cannot output more than 65,536 bytes due to the limitation of [Crypto.getRandomValues()](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues).
My new version splits the output array into 65,536-byte chunks to enable to produce large output without hitting this limitation.
=> Enable Pseudo-Random Number Generator output more than 65,536 bytes

src/core/config/Categories.json, src/core/operations/Shuffle.mjs, tests/operations/index.mjs, tests/operations/tests/Shuffle.mjs
Adding new operation to shuffle entered bytes/characters (code points)/lines.
=> Add new operation: Shuffle

src/core/operations/ParseASN1HexString.mjs, src/core/operations/ParseX509Certificate.mjs
fix #1355
fix #1203
The underlying ASN.1 and X509 parser library `jsrsasign` doesn't look supporting uppercase hex string.
[jsrsasign/asn1hex-1.1.js at master · kjur/jsrsasign](https://github.com/kjur/jsrsasign/blob/c665ebcebc62cc7e55ffadbf2efec7ef89279b00/src/asn1hex-1.1.js#L840)
Therefore, adding conversion to lowercase before passing to the parser library to avoid trouble.
=> Convert hex string to lowercase before parsing as ASN.1

src/core/lib/Hex.mjs, tests/node/tests/operations.mjs
fix #1211
fix #1285
Have "From Hex" treat the delimiter as delimiter, not what to erase.
This will change the output of "From Hex" for an input `0x12 0x34 0x5 0x6` with delimiter "Auto" from `12 34 56` to `12 34 05 06` (after applying "To Hex").
I think the latter output is more natural.
Note that this change breaks some test cases that uses non-hexadecimal strings like `"some key"` with `"Hex"` option.
Such input didn't make sense for me, so I changed thiese cases to use `"utf8"` option instead.
Please let me know if you don't agree.
=> Have "From Hex" treat the delimiter as delimiter, not what to erase

src/core/operations/Reverse.mjs
fix #1181
Changing the behavior of "Character" option in the "Reverse" operation to actually reverse characters.
(Strictly speaking, this version is reversing by code points. Multi-code-point characters like 1️⃣ and 👨‍👨‍👦 will be broken)
Also adding "Byte" option that behaves as previous "Character" option.
=> Make "Reverse by character" actually reverse by character

src/core/operations/UNIXTimestampToWindowsFiletime.mjs, src/core/operations/WindowsFiletimeToUNIXTimestamp.mjs
fix #1354
* Hex output: add 0 to proper position and always output even number of digits
* Hex input: treat odd number of digits like `123` like "From Hex" operation does: `12 03`
=> Improve treatment of Hex (little endian) in Windows Filetime converters

src/core/operations/ViewBitPlane.mjs
fix  #1229
[`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) doesn't have a property `length`, so this part will prevent it from showing resulting image.
https://github.com/gchq/CyberChef/blob/ed8bd34915a70e15def593df4105a7f112b2ff69/src/core/operations/ViewBitPlane.mjs#L93
I changed this line to use `byteLength`, which `ArrayBuffer` has, to enable displaying the result.
=> Use byteLength instead of length to check validity of ArrayBuffer in "View Bit Plane"

src/core/operations/ParseX509Certificate.mjs
Sample input (generated exclusively for this demo):
```
-----BEGIN RSA PRIVATE KEY-----
MIGqAgEAAiEAqEyL5PMVCPjoKZyZfA1bEV7SaMvgcYByNbqb7kt/mGcCAwEAAQIh
AIdRdLHTWThrmY/LoAUEYBFbIi+fNq1b/1yBybRIgcNBAhEA2sdJBnhagHAnRu1j
MB1RNwIRAMTuq6v/HrYtwjryP1i5SlECEGq3iwd87ah5DK+sXBW8N0ECECmHGvR+
K//GznqXsvwGtsECEFrG+GuzNG2Un/o/hMDeyj4=
-----END RSA PRIVATE KEY-----
```
"Parse X.509 certificate" in current version yields this output for this input:
```
Parse X.509 certificate - TypeError in https://gchq.github.io/CyberChef/modules/PublicKey.js on line 2.<br><br>Message: t is null
```
This looked confusing for me, so I added a try-catch statement to have the operation yield this output instead:
```
Parse X.509 certificate - Certificate load error (non-certificate input?)
```
=> Have "Parse X.509 certificate" emit user-friendly message on certificate load error

src/core/operations/GenerateQRCode.mjs
It is specified that a margin of 4 or more modules is required for QR Code.
[Point for determining the code area | QRcode.com | DENSO WAVE](https://www.qrcode.com/en/howto/code.html)
The default setting of "Generate QR Code" operation was adding only a margin of 2 modules, so I changed this to 4 modules to meet the specification.
---
QR Code is registered trademark of [DENSO WAVE INCORPORATED](http://www.denso-wave.com/en/).
=> Put required margin for QR Code by default

src/core/operations/ParseASN1HexString.mjs
Example input:
```
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDH0ZadSjjtAOHcy5aweF8U4iJr
Pn/h2c/0a2ZEEretWbmzpQ0QuUE+jeLVZnPnFbC6KnqeZ3lIK8+iuVAyjGk9po3e
uP/pSsBin0sc9MMez2OYfOlMaShsqY9ciyKRt+Z56nmP17ssBEHJkoEV86R7hrwu
YbYbLRC2a3/CgG6PNQIDAQAB
-----END PUBLIC KEY-----
```
Recipe:
[PEM to Hex, Parse ASN.1 hex string - CyberChef](https://gchq.github.io/CyberChef/#recipe=PEM_to_Hex%28%29Parse_ASN.1_hex_string%280,32%29&input=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FESDBaYWRTamp0QU9IY3k1YXdlRjhVNGlKcgpQbi9oMmMvMGEyWkVFcmV0V2JtenBRMFF1VUUramVMVlpuUG5GYkM2S25xZVozbElLOCtpdVZBeWpHazlwbzNlCnVQL3BTc0JpbjBzYzlNTWV6Mk9ZZk9sTWFTaHNxWTljaXlLUnQrWjU2bm1QMTdzc0JFSEprb0VWODZSN2hyd3UKWWJZYkxSQzJhMy9DZ0c2UE5RSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBL …
=> Fix the name of the option used in "Parse ASN.1 hex string"

src/core/lib/Sort.mjs, src/core/operations/Sort.mjs
I added value Length to the Order option of the Sort operation.
This sorts lines/fields by their length.
Example of use: use the strings operation to extract strings from a malware sample, and then sort those strings by length.
=> Operation Sort: added value Length to option Order

src/core/operations/Fletcher32Checksum.mjs, src/core/operations/Fletcher64Checksum.mjs, tests/operations/index.mjs, tests/operations/tests/FletcherChecksum.mjs, tests/operations/tests/GenerateAllHashes.mjs
fix #1316
* Operate on 16/32-bit words, not bytes
* Add tests
=> fix Fletcher-32/64 Checksum

src/core/config/Categories.json, src/core/operations/CMAC.mjs, tests/operations/index.mjs, tests/operations/tests/CMAC.mjs
=> Add new operation: CMAC

src/core/Utils.mjs, src/core/config/Categories.json, src/core/operations/ChaCha.mjs, tests/operations/index.mjs, tests/operations/tests/ChaCha.mjs
This adds the ChaCha stream cipher. I've chosen to support both the '[original construction](https://cr.yp.to/chacha/chacha-20080128.pdf)' and ChaCha20 as specified in [RFC-8439](https://datatracker.ietf.org/doc/html/rfc8439) (i.e., with a 32-bit instead of a 64-bit counter). Poly1305 may follow separately; I considered whether to combine the two in a single operation, but decided that ChaCha would be of individual interest.
I claim no proficiency in Javascript, and am happy to take any pointers (especially related to type conversions). In particular, this pull request also adds functions to the Utils module to convert between integers and bytes (much like Python's `int.to_bytes` and `int.from_bytes`) ― I was unable to find built-in functionality for this.
=> Add ChaCha stream cipher operation

src/core/config/Categories.json, src/core/operations/AESKeyUnwrap.mjs, src/core/operations/AESKeyWrap.mjs, tests/operations/index.mjs, tests/operations/tests/AESKeyWrap.mjs
=> Add new operations: AES Key Wrap/Unwrap

package-lock.json, package.json, src/core/config/Categories.json, src/core/operations/Argon2.mjs, src/core/operations/Argon2Compare.mjs, tests/node/tests/operations.mjs, webpack.config.js
Closes #608.
Add Argon2 operations for computing and comparing [Argon2](https://wikipedia.org/wiki/Argon2) password hashes.
Uses [antelle/argon2-browser](https://github.com/antelle/argon2-browser).
=> Add Argon2 hash operations

src/web/utils/statusBar.mjs
Thanks for creating this app. I really like it.
I noticed after upgrading to v10, the newly added hover for the baking time is a bit off. I think it should be removed.
Before:
After:
=> fix: incorrect hover on baking info

.gitignore, src/core/config/Categories.json, src/core/lib/LZNT1.mjs, src/core/operations/LZNT1Decompress.mjs, src/web/html/index.html, tests/node/tests/operations.mjs, tests/operations/index.mjs, tests/operations/tests/LZNT1Decompress.mjs
Introduces support for [LZNT1](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-xca/5655f4a3-6ba4-489b-959f-e1f407c52f15) decompression, commonly leveraged by malware through [`RtlDecompressBuffer`](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtldecompressbuffer) (closes #534).
The decompression logic is ported from [`go-ntfs`](https://github.com/Velocidex/go-ntfs/blob/master/parser%2Flznt1.go), the test data is similar to [`malduck`](https://github.com/CERT-Polska/malduck/blob/master/tests/test_compression.py)'s.
=> Add support for LZNT1 decompression.

src/core/operations/ExtractIPAddresses.mjs
IPv6 regexp shouldn't match IPv4 address.
[https://gchq.github.io/CyberChef/#recipe=Extract_IP_addresses(false,true,false,false,false,false)&input=MTI3LjAuMC4xLCBmZTgwOjoy](https://gchq.github.io/CyberChef/#recipe=Extract_IP_addresses(false,true,false,false,false,false)&input=MTI3LjAuMC4xLCBmZTgwOjoy)
=> Fix ExtractIPAddresses IPv6 regexp

src/core/config/Categories.json, src/core/operations/FileTree.mjs, tests/operations/tests/FileTree.mjs
Added file tree functionality. If you want me to change anything or add anything then please let me know.
=> Added file tree functionality

src/web/stylesheets/operations/json.css
Close #1707
Looks like that using `display: contents;` in summary may cause some weird effect.
https://github.com/whatwg/html/issues/1839#issuecomment-251574911
This PR:
1. remove `display: contents;`
2. add `list-style: none;` for hiding the default disclosure triangle
3. add `display: inline;` to ensure consistent layout
=> Fix JSON folder folding in Firefox

package-lock.json, package.json, src/core/operations/JWTSign.mjs
As per npm audit, jwonwebtoken has a moderate level vuln:
```
jsonwebtoken  <=8.5.1
Severity: moderate
jsonwebtoken unrestricted key type could lead to legacy keys usage  - https://github.com/advisories/GHSA-8cf7-32gw-wr33
jsonwebtoken's insecure implementation of key retrieval function could lead to Forgeable Public/Private Tokens from RSA to HMAC - https://github.com/advisories/GHSA-hjrf-2m68-5959
jsonwebtoken vulnerable to signature validation bypass due to insecure default algorithm in jwt.verify() - https://github.com/advisories/GHSA-qwph-4952-7xr6
fix available via `npm audit fix --force`
Will install jsonwebtoken@9.0.2, which is a breaking change
node_modules/jsonwebtoken
```
This PR:
* Updates jsonwebtoken to latest 9+ version
* Updates JWTSign operation for backwards …
=> Updated jsonwebtoken dependency to 9+

package-lock.json, package.json, src/core/operations/CSSSelector.mjs, src/core/operations/XPathExpression.mjs
Output from npm audit from current master shows critical severity for xmldom library:
```
xmldom  *
Severity: critical
xmldom allows multiple root nodes in a DOM - https://github.com/advisories/GHSA-crh6-fp67-6883
Misinterpretation of malicious XML input - https://github.com/advisories/GHSA-5fg8-2547-mr8q
No fix available
node_modules/xmldom
```
As per the package github page (https://github.com/xmldom/xmldom), they changed the namespace to `@xmldom/xmldom` so this PR updates that dependency in package.json and usage of the package in the source.
=> Updated xmldom package to new namespace for vuln remediation

src/core/vendor/DisassembleX86-64.mjs
Update the disassembler to the most recent version: https://github.com/Recoskie/X86-64-Disassembler-JS/releases/tag/V2.3
=> X86-64-Disassembler-JS: Fixed right shift 32 problem

src/core/operations/BlowfishDecrypt.mjs, src/core/operations/BlowfishEncrypt.mjs, tests/operations/tests/Crypt.mjs
This fixes https://github.com/gchq/CyberChef/issues/930 by correcting the key size validation. Tests have also been added for key sizes other than 8 bytes.
=> Allow variable key sizes for Blowfish

src/core/config/Categories.json, src/core/operations/XXTEA.mjs, tests/operations/tests/XXTEA.mjs
Supports XXTEA encryption #1349
=> Xxtea encryption

tests/browser/02_ops.js
I hate to just disable tests, but this issue is not reproducible locally and has sat unfixed for over a year now.
=> Disable 'Extract ID3' Nightwatch tests

src/core/lib/CipherSaber2.mjs, tests/operations/tests/CipherSaber2.mjs
Previously the generated key was invalid because an Uint8Array was concatenated into a normal array but that wasn't supported by the concat function.
Effectively the IV was discarded so the cipher did not work :)
This should fix https://github.com/gchq/CyberChef/issues/1723
=> Fix Ciphersaber2 key concatenation

src/core/operations/DeriveEVPKey.mjs
As pointed out in https://github.com/gchq/CyberChef/issues/1593, CryptoJS treats strings as Utf8, so for binary strings, Latin1 needs to be used.
This PR should fix that issue, and there are no other instances of raw strings being passed to CryptoJS methods.
=> Fix CryptoJS argument passing in DeriveEVPKey

package-lock.json, package.json, src/core/operations/JWTSign.mjs
=> Revert "Updated jsonwebtoken dependency to 9+"

src/core/config/Categories.json, src/core/operations/ParseCSR.mjs, tests/operations/index.mjs, tests/operations/tests/ParseCSR.mjs
Added new operation _Parse CSR_ under _Public Key_.
The operation parses a PEM formatted Certificate Signing Request (CSR) for an X.509 certificate and visualize it.
It is limited to RSA public key algorithms only as this is the only one supported for CSR in node-forge as of 1.3.1.
Another PR #381 that implements the same operation has been stale for a while.
Sample input:
```
-----BEGIN CERTIFICATE REQUEST-----
MIIDtzCCAp8CAQAwgZgxCzAJBgNVBAYTAlVLMRcwFQYDVQQIDA5HcmVhdGVyIExv
bmRvbjEPMA0GA1UEBwwGTG9uZG9uMRwwGgYDVQQKDBNHZW5lcmljIENvcnBvcmF0
aW9uMRkwFwYDVQQLDBBTcGVjaWFsIFByb2R1Y3RzMSYwJAYDVQQDDB13d3cuZ2Vu
ZXJpYy1jb3Jwb3JhdGlvbi5jby51azCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBALLy/tgblvngPZ44cKqnVe01KdxTc6DVmdL2SNG1NLNsDS6IidJi2t/S …
```
=> Add new operation: Parse Certificate Signing Request (CSR)

src/core/config/Categories.json, src/core/operations/ExtractHashes.mjs, tests/operations/index.mjs, tests/operations/tests/ExtractHashes.mjs
References https://github.com/gchq/CyberChef/issues/466
Adds operation for extracting hash values from text blocks. Searches text for hashes based on length.  
Options for:
- Searching for hashes of all lengths. Potential hash lengths taken from "Analyse Hashes" operation. 
- Displaying total hashes found.
If it makes more sense to select hash types by name from a dropdown rather than by character length, I can change that.
=> Operation: Extract Hash Values

src/web/stylesheets/layout/_modals.css
**Issue**
[Issue #1718](https://github.com/gchq/CyberChef/issues/1718)
This PR aims to solve some of the the 'limited keyboard interaction' outlined in section 1 of **keyboard Navigation** in the issue linked above, focusing on the _Options_ dialog box. E.g. Unclear navigation through the checkbox items as there is no visual focus of the elements for keyboard users.
**Code changes:**
- Added CSS styling for form group checkbox elements to match styling of mouse hover
**User-facing changes:**
- checkbox element labels change colour on focus with keyboard navigation
**To replicate:**
- Open options dialog with mouse click (keyboard functionality is being implemented in separate PR)
- `Tab` through checkbox elements
- Expect labels to change on focus and match styling of mouse hover
=> Accessibility - On focus CSS styling within options dialog to match mouse hover

src/core/config/Categories.json, src/core/operations/JWKToPem.mjs, src/core/operations/PEMToJWK.mjs, tests/operations/index.mjs, tests/operations/tests/JWK.mjs
Transforms a key in PEM format to a JSON Web key or
a JWK back to its PEM format
=> New Operations: JWK conversion from/to PEM

src/core/config/Categories.json, src/core/operations/PubKeyFromCert.mjs, src/core/operations/PubKeyFromPrivKey.mjs, tests/operations/index.mjs, tests/operations/tests/PubKeyFromCert.mjs, tests/operations/tests/PubKeyFromPrivKey.mjs
Add two new operations. One operation to get the public key of a given certificate and another one to get the public key for a given private key.
=> Get Public Key from a Certificate or from a Private Key

src/core/lib/Ciphers.mjs, tests/browser/02_ops.js
The affine multiplier is checked to be coprime to 26 in affine decode, but not encode, so this PR address that. It [doesn't make sense](https://en.wikipedia.org/wiki/Affine_cipher#Encryption) to allow non-coprime values in the cipher, as the resulting ciphertext is invalid and unable to be decoded.
=> Require (a, 26) to be coprime in affine encode

src/web/App.mjs, src/web/waiters/WorkerWaiter.mjs, tests/browser/01_io.js
The current autobake design is that if the bake has already started, input updates do nothing.. This has proven to be counterintuitive, causing the issue https://github.com/gchq/CyberChef/issues/1467 to be reported (I think). Personally I'd also expect the autobake option to cause the previous bake to be aborted and restart with the new input..
Here's my attempt (at least there was an attempt...) at implementing this. The code is messy since I initially wanted to preserve the loader screen when changing input (canceling just the workers), but if the waiter has more than 1 output then I found that I need to call `cancelBake` anyway..
I was also able to test this behaviour thanks to the `Sleep` operation which makes reproducing the issue deterministic.
=> Abort the previous bake when attempting the next autobake

src/core/config/Categories.json, src/core/operations/ParseX509CRL.mjs, tests/operations/tests/ParseX509CRL.mjs
Added a new operation `Parse X.509 CRL` for parsing X.509 Certificate Revocation Lists. This new operation leverages the existing dependency on [jsrsasign](https://kjur.github.io/jsrsasign/) to parse the CRLs and formats the output in a human readable format. Output structure is comparable to what is being returned when parsed with [openssl v3.0.0](https://github.com/openssl/openssl/tree/openssl-3.0.13).
___Please select the option that best describes the change:___
Tested locally on my machine with various CRLs. Following are some outputs from those tests:
=> Add operation for parsing X.509 CRLs

src/node/config/scripts/generateNodeIndex.mjs
Error output points to incorrect directory.
=> Corrected path to generateNodeIndex.mjs

src/core/operations/JWTSign.mjs, tests/operations/tests/JWTSign.mjs
Expose the 'header' option of the [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken?tab=readme-ov-file#usage) module as an ingredient. This allows for [adding and overwriting](https://github.com/auth0/node-jsonwebtoken/blob/bc28861f1fa981ed9c009e29c044a19760a0b128/sign.js#L97) JWT header fields such as `type` or `kid`.
Not sure how you typically handle JSON input like this. Should it be sanitized before passing it into the jwt library?
=> Add 'header' ingredient to JWT Sign operation

src/core/operations/AddLineNumbers.mjs
For issue: https://github.com/gchq/CyberChef/issues/1865
Very simple change. Default offset is 0, so this should only add to existing functionality
I think this is particularly useful for including line numbers for code snippets when the original source is important.
eg:
=> add offset field to 'Add Line Numbers' operation

src/core/operations/LuhnChecksum.mjs, tests/operations/tests/LuhnChecksum.mjs
Updated luhn checksum operation to work with different bases from 2-36 (english alphabet) according to [Luhn mod N algorithm](https://en.wikipedia.org/wiki/Luhn_mod_N_algorithm).
=> Updated luhn checksum operation to work with different bases

src/core/operations/DESDecrypt.mjs, src/core/operations/DESEncrypt.mjs, src/core/operations/TripleDESDecrypt.mjs, src/core/operations/TripleDESEncrypt.mjs, tests/node/tests/nodeApi.mjs, tests/operations/tests/Crypt.mjs
Fixes https://github.com/gchq/CyberChef/issues/1843.
=> fix: DES/Triple DES - misleading error messages

src/core/config/Categories.json, src/core/operations/MIMEDecoding.mjs, tests/operations/index.mjs, tests/operations/tests/MIMEDecoding.mjs
Addresses https://github.com/gchq/CyberChef/issues/538
Added support for decoding MIME RFC2047 encoded headers.
=> Feature: MIME RFC2047 Decoding

src/web/waiters/OptionsWaiter.mjs
- Load the user's preferred color scheme if the URL contains an invalid theme.
- Fix: #1996 
visit: https://gchq.github.io/CyberChef?theme=foo where foo is not a valid theme name.
It does not occur when foo is a valid theme name or for https://gchq.github.io/CyberChef
Expected behaviour
Cyberchef should probably give an "invalid theme" message or load with the default theme.
=> Load the user's preferred color scheme if the URL contains an invalid theme

package-lock.json, package.json, src/web/waiters/RecipeWaiter.mjs
- Fix(RecipeWaiter): sanitize user input in addOperation to prevent XSS
- Fix: #1802 , Fix: #1468  
- Using `innerHTML` directly introduces a potential XSS vulnerability by allowing injection of malicious code. 
- A recommended solution is to sanitize the input using the **DOMPurify** library: https://www.npmjs.com/package/dompurify. 
- **If relying on external libraries is not preferred, please let me know and I can suggest an alternative approach**.
https://github.com/user-attachments/assets/42ede87d-b5c8-44dc-bcbf-e6bd244953d9
https://github.com/user-attachments/assets/98d67b1a-f758-4b96-ae83-577396bfe249
- https://gchq.github.io/CyberChef#recipe=%3Cimg_src%3dx_onerror%3d'alert%601%60'/%3E('Space',false)Generate_all_hashes()&input=MzA1MTczMTA5
- …
=> Fix(RecipeWaiter): sanitize user input in addOperation to prevent XSS

src/core/lib/Base32.mjs, src/core/operations/FromBase32.mjs, src/core/operations/ToBase32.mjs, tests/operations/index.mjs, tests/operations/tests/Base32.mjs
As per [RFC 4648 section 7](https://www.rfc-editor.org/rfc/rfc4648#section-7), Base32 also has a "Hex Extended" alphabet of "0-9A-V=".
I've implemented this option, and also added tests for Base32 as it was the only different base encoding missing test cases (which all pass).
=> Add Base32 Hex Extended Alphabet and Base32 Tests.

.github/workflows/releases.yml
Workflow task `Publish to NPM` was disabled for testing on a fork, however we should re-enable on main before the next release.
=> Re-enable Npm Release in github workflows

src/core/operations/ECDSAVerify.mjs, tests/operations/tests/ECDSA.mjs
Hi,
ECDSA signature verification had no option for the incoming message format (like RSA Sign Verify). I have added it and created some test.
Thank you for this wonderful tool,
Best regards
=> Add to ECDSA Verify the message format

src/core/config/Categories.json, src/core/operations/GenerateAllChecksums.mjs, src/core/operations/GenerateAllHashes.mjs, tests/operations/index.mjs, tests/operations/tests/GenerateAllChecksums.mjs, tests/operations/tests/GenerateAllHashes.mjs
Hi,
I have corrected "Generate all hashes" operation by removing the checksums. I've also created a new "Generate all checksums" operation with its corresponding test.
Thank you for this wonderful tool,
Best regards
=> Add all checksum operation

src/core/operations/URLDecode.mjs, tests/operations/index.mjs, tests/operations/tests/URLEncodeDecode.mjs
Adds option to disable treating "+" character as space in URLDecode operation. Fixes issue https://github.com/gchq/CyberChef/issues/1477
Changes originate from https://github.com/gchq/CyberChef/pull/1483
=> Add toggle "+" character to URLDecode operation

src/core/operations/ExtractIPAddresses.mjs, tests/operations/index.mjs, tests/operations/tests/ExtractIPAddresses.mjs
Addresses bug report #2008 
Added explicit support for octal IP addresses.
Changed approach to IPv4 regex to be string manipulation generated.
Added some unit tests for IP address parsing - probably not full coverage.
Added lookahead and lookbehind tricks to resolve warned issue that 1.2.3.256 would still be extracted as 1.2.3.25. Now only accepts valid IP addresses. Warning replaced with clause about infinite length dotted decimal forms.
=> Octal ip addresses

src/node/api.mjs
This ensures that when recipes are calling ingredients without arguments using the API, the proper defaults are used.
When used in a browser, CyberChef fills in the proper defaults when the ingredient form is rendered (and subsequently alters the url), however, unit tests could still fail. E.g., calling `generate_UUID()` should use 'v4' as the default UUID version, but would pick 'v1' (the first option in the list). See also #2011.
=> fix: use defaultIndex instead of 0 in transformArgs

README.md
This PR added more clarity to the build instructions in the README.  
It now mentions
- Docker installation prerequisite 
- How to navigate to the project using localhost
This PR closes [Issue #1870](https://github.com/gchq/CyberChef/issues/1870)
=> Add more clear build instructions
